import java.io.*;
import java.net.*;
import java.util.*;

class MT2018001_MT2018111_TCPServer{
public static void main(String args[]) throws IOException{
ServerSocket ss=new ServerSocket(1254);
Socket cl=ss.accept();
DataInputStream di= new DataInputStream( cl.getInputStream());
DataOutputStream dos=new DataOutputStream(cl.getOutputStream());
int arr[]=new int[5];
System.out.println("Marks generated by Client: ");
for(int i=0;i<5;i++){
arr[i]=di.readInt();
System.out.println(arr[i]);
}
Arrays.sort(arr);
System.out.println("Sorted array is: ");
for(int i=0;i<arr.length;i++)
  System.out.println(arr[i]);
float sum=0;
for(int i=0;i<5;i++)
	sum=sum+arr[i];
float avg=sum/5;
System.out.println("average of five marks: "+avg);
System.out.println("Sending sorted marks and average to client");
for(int i=0;i<5;i++){
	dos.writeInt(arr[i]);
}
dos.writeFloat(avg);
di.close();
dos.close();
cl.close();

}

}
